export const ACTIONS = {
  SET_ROUTE: "SET_ROUTE",
  SET_CURRENT_ROUTE: "SET_CURRENT_ROUTE",
  SET_CURRENT_CORDS: "SET_CURRENT_CORDS",
  GET_CARGO_DATA: "GET_CARGO_DATA",
  SET_CARGO_DATA: "SET_CARGO_DATA",
  PATCH_CARGO_DATA: "PATCH_CARGO_DATA",
  SET_CITIES_DATA: "SET_CITIES_DATA",
};
